http:
  address: 0.0.0.0:34198
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: false
input:
  type: nats_stream
  nats_stream:
    ack_wait: 30s
    batching:
      byte_size: 0
      condition:
        type: static
        static: false
      count: 1
      period: ""
      processors: []
    client_id: otf_publish_level_maps
    cluster_id: test-cluster
    durable_name: #benthos_offset
    max_inflight: 1024
    queue: #benthos_queue
    start_from_oldest: true
    subject: otf.maps.level
    unsubscribe_on_close: false
    urls:
      - nats://127.0.0.1:4222
buffer:
  type: none
  none: {}
pipeline:
  processors:
    - bloblang: |
        root = this.original
    # - archive:
        # format: json_array
  threads: 1

# output:
#   files:
#     path: ./msgs/${!count("files")}-${!timestamp_unix_nano()}.json

output:  
  type: http_client
  http_client:
    backoff_on:
      - 429
    basic_auth:
      enabled: false
      password: ""
      username: ""
    batching:
      count: 100
      period: 1s
      processors: 
        - archive:
            format: json_array
    copy_response_headers: false
    drop_on: []
    headers:
      Content-Type: application/json
      Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkZW1vIiwiY25hbWUiOiJsZXZlbGxpbmdNYXBzIiwidW5hbWUiOiJuc2lwT3RmTGV2ZWwifQ.FJkGIO60nqWO2-dg4gacsbuqamKYNurRHTGoiwy_Oto
    max_in_flight: 1
    max_retry_backoff: 300s
    oauth:
      access_token: ""
      access_token_secret: ""
      consumer_key: ""
      consumer_secret: ""
      enabled: false
      request_url: ""
    propagate_response: false
    rate_limit: ""
    retries: 3
    retry_period: 1s
    successful_on: []
    timeout: 5s
    tls:
      client_certs: []
      enabled: false
      root_cas_file: ""
      skip_cert_verify: false
    url: http://localhost:1323/n3/publish
    verb: POST

resources:
  caches: {}
  conditions: {}
  inputs: {}
  outputs: {}
  processors: {}
  rate_limits: {}
logger:
  prefix: benthos
  level: INFO
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos
metrics:
  type: http_server
  http_server:
    prefix: benthos
tracer:
  type: none
  none: {}
shutdown_timeout: 20s

